import type { Schema } from "./types";

export function genEffectsInterface(schema: Schema): string {
  const events = new Set<string>();
  const notifyTemplates = new Set<string>();
  const calls = new Set<string>();

  for (const ops of Object.values(schema.operations)) {
    for (const op of Object.values(ops)) {
      for (const e of op.effects) {
        if (e.emit) events.add(e.emit);
        if (e.notify) notifyTemplates.add(e.notify.template);
        if (e.call) calls.add(`${e.call.service}.${e.call.action}`);
      }
    }
  }

  return `// Generated by schema/codegen.ts — do not edit

// Events emitted by operations
export type Event =
${[...events].map(e => `  | "${e}"`).join("\n") || "  | never"};

// Notification templates
export type NotifyTemplate =
${[...notifyTemplates].map(t => `  | "${t}"`).join("\n") || "  | never"};

// External service calls
export type ServiceCall =
${[...calls].map(c => `  | "${c}"`).join("\n") || "  | never"};

// Effect handlers interface
export interface EffectHandlers {
  emit(event: Event, data: unknown): Promise<void>;
  notify(channel: string, template: NotifyTemplate, to: string, data: unknown): Promise<void>;
  call(service: string, action: string, data: unknown): Promise<unknown>;
}
`;
}
