import type { Schema, WebhookSigningMetadata } from "./types";
import { hasCommerceBookingAliases, hasCommerceWorkflow } from "./utils";

function webhookSigningConfig(schema: Schema): WebhookSigningMetadata {
  return schema.integrations?.webhookEffects?.signing || {
    enabled: true,
    algorithm: "sha256",
    payload: "timestamp.body",
    signatureHeader: "X-OpenB2C-Signature",
    timestampHeader: "X-OpenB2C-Timestamp",
    toleranceSeconds: 300,
  };
}

export function genEffectsInterface(schema: Schema): string {
  const events = new Set<string>();
  const notifyTemplates = new Set<string>();
  const calls = new Set<string>();
  const webhookSigning = webhookSigningConfig(schema);

  for (const ops of Object.values(schema.operations)) {
    for (const op of Object.values(ops)) {
      for (const e of op.effects) {
        if (e.emit) events.add(e.emit);
        if (e.notify) notifyTemplates.add(e.notify.template);
        if (e.call) calls.add(`${e.call.service}.${e.call.action}`);
      }
    }
  }
  if (hasCommerceWorkflow(schema)) {
    events.add("commerce.order_created");
    events.add("commerce.order_paid");
    events.add("commerce.payment_failed");
    notifyTemplates.add("receipt");
    calls.add("payment.create_intent");
    calls.add("analytics.track_purchase");
  }
  if (hasCommerceBookingAliases(schema)) {
    events.add("booking.reserved");
    events.add("booking.paid");
    events.add("booking.payment_failed");
  }

  return `// Generated by schema/codegen.ts — do not edit

import { Database } from "bun:sqlite";
import type { Effect } from "./services";

// Events emitted by operations
export type Event =
${[...events].map(e => `  | "${e}"`).join("\n") || "  | never"};

// Notification templates
export type NotifyTemplate =
${[...notifyTemplates].map(t => `  | "${t}"`).join("\n") || "  | never"};

// External service calls
export type ServiceCall =
${[...calls].map(c => `  | "${c}"`).join("\n") || "  | never"};

export type EffectStatus = "pending" | "succeeded" | "failed" | "dead_letter";

export interface EffectContext {
  source: "rest" | "mcp" | "retry";
  operation: string;
  entity?: string;
  recordId?: number;
  result?: unknown;
  idempotencyKey?: string;
  maxAttempts?: number;
}

export interface EffectAttempt {
  id: number;
  idempotency_key: string;
  effect_type: string;
  payload_json: string;
  context_json: string;
  status: EffectStatus;
  attempts: number;
  max_attempts: number;
  next_attempt_at: string | null;
  last_error: string | null;
  result_json: string | null;
  created_at: string;
  updated_at: string;
}

export interface DispatchSummary {
  attempted: number;
  succeeded: number;
  failed: number;
  deadLetter: number;
  skipped: number;
}

export interface RuntimeEffectHandlers {
  emit(event: Event, data: unknown, context: EffectContext): Promise<unknown>;
  notify(channel: string, template: NotifyTemplate, to: string, data: unknown, context: EffectContext): Promise<unknown>;
  call(service: string, action: string, data: unknown, context: EffectContext): Promise<unknown>;
  webhook(url: string, payload: unknown, context: EffectContext): Promise<unknown>;
  email(message: { channel: string; template: NotifyTemplate; to: string; data: unknown }, context: EffectContext): Promise<unknown>;
  payment(action: string, payload: unknown, context: EffectContext): Promise<unknown>;
}

const DEFAULT_MAX_ATTEMPTS = Math.max(parseInt(process.env.EFFECT_MAX_ATTEMPTS || "3", 10) || 3, 1);
const BASE_RETRY_DELAY_MS = Math.max(parseInt(process.env.EFFECT_RETRY_DELAY_MS || "1000", 10) || 1000, 1);
const MAX_RETRY_DELAY_MS = Math.max(parseInt(process.env.EFFECT_MAX_RETRY_DELAY_MS || "300000", 10) || 300000, BASE_RETRY_DELAY_MS);
const WEBHOOK_SIGNATURE_ENABLED = ${webhookSigning.enabled ? "true" : "false"};
const WEBHOOK_SIGNATURE_ALGORITHM = ${JSON.stringify(webhookSigning.algorithm)};
const WEBHOOK_SIGNATURE_HEADER = ${JSON.stringify(webhookSigning.signatureHeader)};
const WEBHOOK_TIMESTAMP_HEADER = ${JSON.stringify(webhookSigning.timestampHeader)};
const DEFAULT_WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = ${Number.isFinite(webhookSigning.toleranceSeconds) ? webhookSigning.toleranceSeconds : 300};

function hashString(value: string): string {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function json(value: unknown): string {
  return JSON.stringify(value ?? null);
}

function parseJson<T>(value: string): T {
  return JSON.parse(value) as T;
}

export type WebhookSignatureHeaders = Pick<Headers, "get"> | Record<string, string | undefined>;

function hex(bytes: ArrayBuffer): string {
  return Array.from(new Uint8Array(bytes)).map(b => b.toString(16).padStart(2, "0")).join("");
}

function safeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return result === 0;
}

async function hmacSha256Hex(secret: string, body: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  return hex(await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(body)));
}

function signatureHeaderValue(headers: WebhookSignatureHeaders, name: string): string {
  const getter = (headers as Pick<Headers, "get">).get;
  if (typeof getter === "function") return getter.call(headers, name) || "";
  const record = headers as Record<string, string | undefined>;
  return record[name] || record[name.toLowerCase()] || "";
}

function webhookSignatureToleranceSeconds(): number {
  return Math.max(parseInt(process.env.WEBHOOK_SIGNATURE_TOLERANCE_SECONDS || String(DEFAULT_WEBHOOK_SIGNATURE_TOLERANCE_SECONDS), 10) || DEFAULT_WEBHOOK_SIGNATURE_TOLERANCE_SECONDS, 1);
}

export async function webhookSigningHeaders(body: string): Promise<Record<string, string>> {
  if (!WEBHOOK_SIGNATURE_ENABLED) return {};
  const secret = process.env.WEBHOOK_SIGNING_SECRET;
  if (!secret) {
    if (process.env.NODE_ENV === "production") {
      throw new Error("WEBHOOK_SIGNING_SECRET is required in production for webhook effects");
    }
    return {};
  }
  const timestamp = Math.floor(Date.now() / 1000).toString();
  const signature = await hmacSha256Hex(secret, timestamp + "." + body);
  return {
    [WEBHOOK_TIMESTAMP_HEADER]: timestamp,
    [WEBHOOK_SIGNATURE_HEADER]: WEBHOOK_SIGNATURE_ALGORITHM + "=" + signature,
  };
}

export async function verifyOpenB2CWebhookSignature(
  headers: WebhookSignatureHeaders,
  body: string,
  secret = process.env.WEBHOOK_SIGNING_SECRET || "",
  toleranceSeconds = webhookSignatureToleranceSeconds(),
): Promise<boolean> {
  if (!WEBHOOK_SIGNATURE_ENABLED) return false;
  if (!secret) return false;
  const timestamp = signatureHeaderValue(headers, WEBHOOK_TIMESTAMP_HEADER);
  const signatureHeader = signatureHeaderValue(headers, WEBHOOK_SIGNATURE_HEADER).trim();
  const signaturePrefix = WEBHOOK_SIGNATURE_ALGORITHM + "=";
  const signature = signatureHeader.startsWith(signaturePrefix)
    ? signatureHeader.slice(signaturePrefix.length)
    : signatureHeader.replace(/^sha256=/, "");
  if (!timestamp || !signature) return false;
  const timestampMs = Number(timestamp) * 1000;
  if (!Number.isFinite(timestampMs)) return false;
  if (toleranceSeconds > 0 && Math.abs(Date.now() - timestampMs) > toleranceSeconds * 1000) return false;
  return safeEqual(signature, await hmacSha256Hex(secret, timestamp + "." + body));
}

export function ensureEffectTables(db: Database) {
  db.run(\`
    CREATE TABLE IF NOT EXISTS openb2c_effect_attempt (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      idempotency_key TEXT NOT NULL UNIQUE,
      effect_type TEXT NOT NULL,
      payload_json TEXT NOT NULL,
      context_json TEXT NOT NULL,
      status TEXT NOT NULL,
      attempts INTEGER NOT NULL DEFAULT 0,
      max_attempts INTEGER NOT NULL DEFAULT 3,
      next_attempt_at TEXT,
      last_error TEXT,
      result_json TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  \`);
  db.run("CREATE INDEX IF NOT EXISTS openb2c_effect_attempt_status ON openb2c_effect_attempt (status, next_attempt_at)");
}

export const defaultEffectHandlers: RuntimeEffectHandlers = {
  async emit(event, data, context) {
    console.log(JSON.stringify({ level: "info", msg: "effect emitted", event, context, data }));
    return { emitted: event };
  },
  async notify(channel, template, to, data, context) {
    console.log(JSON.stringify({ level: "info", msg: "notification queued", channel, template, to, context, data }));
    return { channel, template, to };
  },
  async call(service, action, data, context) {
    console.log(JSON.stringify({ level: "info", msg: "service call queued", service, action, context, data }));
    return { service, action };
  },
  async webhook(url, payload) {
    if (!url) return { skipped: true, reason: "WEBHOOK_URL not configured" };
    const body = JSON.stringify(payload);
    const res = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json", ...await webhookSigningHeaders(body) },
      body,
    });
    if (!res.ok) throw new Error(\`webhook failed with status \${res.status}\`);
    return { status: res.status };
  },
  async email(message) {
    const url = process.env.EMAIL_WEBHOOK_URL;
    if (!url) return { skipped: true, reason: "EMAIL_WEBHOOK_URL not configured", message };
    const res = await fetch(url, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(message),
    });
    if (!res.ok) throw new Error(\`email dispatch failed with status \${res.status}\`);
    return { status: res.status };
  },
  async payment(action, payload) {
    const provider = process.env.PAYMENT_PROVIDER || "local";
    if (provider !== "local" && !process.env.PAYMENT_API_KEY) {
      throw new Error("PAYMENT_API_KEY is required for configured payment provider");
    }
    return {
      provider,
      action,
      id: \`payment_\${crypto.randomUUID()}\`,
      payload,
    };
  },
};

function effectType(effect: Effect): string {
  return effect.type;
}

function effectPayload(effect: Effect): Record<string, unknown> {
  return effect.payload as Record<string, unknown>;
}

function effectKey(effect: Effect, index: number, context: EffectContext): string {
  const base = context.idempotencyKey
    || [context.source, context.operation, context.recordId ?? "collection"].join(":");
  return \`\${base}:\${index}:\${hashString(json(effect))}\`;
}

function findAttempt(db: Database, key: string): EffectAttempt | null {
  return db.query("SELECT * FROM openb2c_effect_attempt WHERE idempotency_key = ?").get(key) as EffectAttempt | null;
}

function insertAttempt(db: Database, key: string, effect: Effect, context: EffectContext): EffectAttempt {
  db.query(\`
    INSERT OR IGNORE INTO openb2c_effect_attempt
      (idempotency_key, effect_type, payload_json, context_json, status, max_attempts)
    VALUES (?, ?, ?, ?, 'pending', ?)
  \`).run(key, effectType(effect), json(effectPayload(effect)), json(context), context.maxAttempts ?? DEFAULT_MAX_ATTEMPTS);
  const row = findAttempt(db, key);
  if (!row) throw new Error(\`failed to create effect attempt \${key}\`);
  return row;
}

function retryDelay(attempts: number): string {
  const delay = Math.min(BASE_RETRY_DELAY_MS * Math.pow(2, attempts), MAX_RETRY_DELAY_MS);
  return new Date(Date.now() + delay).toISOString();
}

async function executeEffect(effect: Effect, context: EffectContext, handlers: RuntimeEffectHandlers): Promise<unknown> {
  const payload = effectPayload(effect);
  if (effect.type === "emit") {
    return handlers.emit(payload.event as Event, payload, context);
  }
  if (effect.type === "notify") {
    const channel = payload.channel as string;
    const template = payload.template as NotifyTemplate;
    const to = (payload.to as string | undefined) || "customer";
    if (channel === "email") {
      return handlers.email({ channel, template, to, data: payload }, context);
    }
    return handlers.notify(channel, template, to, payload, context);
  }
  if (effect.type === "call") {
    const service = payload.service as string;
    const action = payload.action as string;
    if (service === "webhook") {
      return handlers.webhook(process.env.WEBHOOK_URL || "", { action, payload, context }, context);
    }
    if (service === "payment") {
      return handlers.payment(action, payload, context);
    }
    return handlers.call(service, action, payload, context);
  }
  throw new Error(\`unknown effect type: \${effect.type}\`);
}

async function runAttempt(db: Database, row: EffectAttempt, effect: Effect, context: EffectContext, handlers: RuntimeEffectHandlers): Promise<EffectStatus> {
  if (row.status === "succeeded") return "succeeded";
  if (row.status === "dead_letter" && row.attempts >= row.max_attempts) return "dead_letter";
  try {
    const result = await executeEffect(effect, context, handlers);
    db.query(\`
      UPDATE openb2c_effect_attempt
      SET status = 'succeeded',
          attempts = attempts + 1,
          next_attempt_at = NULL,
          last_error = NULL,
          result_json = ?,
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    \`).run(json(result), row.id);
    return "succeeded";
  } catch (err) {
    const attempts = row.attempts + 1;
    const status: EffectStatus = attempts >= row.max_attempts ? "dead_letter" : "failed";
    db.query(\`
      UPDATE openb2c_effect_attempt
      SET status = ?,
          attempts = attempts + 1,
          next_attempt_at = ?,
          last_error = ?,
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    \`).run(status, status === "dead_letter" ? null : retryDelay(attempts), String(err), row.id);
    return status;
  }
}

function emptySummary(): DispatchSummary {
  return { attempted: 0, succeeded: 0, failed: 0, deadLetter: 0, skipped: 0 };
}

function addStatus(summary: DispatchSummary, status: EffectStatus | "skipped") {
  if (status === "succeeded") summary.succeeded++;
  else if (status === "failed") summary.failed++;
  else if (status === "dead_letter") summary.deadLetter++;
  else summary.skipped++;
}

export async function dispatchEffects(
  db: Database,
  effects: Effect[] = [],
  context: EffectContext,
  handlers: RuntimeEffectHandlers = defaultEffectHandlers
): Promise<DispatchSummary> {
  ensureEffectTables(db);
  const summary = emptySummary();
  for (let i = 0; i < effects.length; i++) {
    const effect = effects[i];
    const key = effectKey(effect, i, context);
    const row = insertAttempt(db, key, effect, context);
    if (row.status === "succeeded") {
      addStatus(summary, "skipped");
      continue;
    }
    summary.attempted++;
    const status = await runAttempt(db, row, effect, context, handlers);
    addStatus(summary, status);
  }
  return summary;
}

export function listEffectAttempts(db: Database, status?: EffectStatus): EffectAttempt[] {
  ensureEffectTables(db);
  if (status) {
    return db.query("SELECT * FROM openb2c_effect_attempt WHERE status = ? ORDER BY id DESC").all(status) as EffectAttempt[];
  }
  return db.query("SELECT * FROM openb2c_effect_attempt ORDER BY id DESC").all() as EffectAttempt[];
}

export async function retryFailedEffects(
  db: Database,
  handlers: RuntimeEffectHandlers = defaultEffectHandlers,
  limit = 50
): Promise<DispatchSummary> {
  ensureEffectTables(db);
  const rows = db.query(\`
    SELECT * FROM openb2c_effect_attempt
    WHERE status IN ('failed', 'dead_letter')
      AND attempts < max_attempts
    ORDER BY updated_at ASC
    LIMIT ?
  \`).all(limit) as EffectAttempt[];
  const summary = emptySummary();
  for (const row of rows) {
    summary.attempted++;
    const effect = { type: row.effect_type, payload: parseJson(row.payload_json) } as Effect;
    const context = { ...parseJson<EffectContext>(row.context_json), source: "retry" as const };
    const status = await runAttempt(db, row, effect, context, handlers);
    addStatus(summary, status);
  }
  return summary;
}
`;
}
