import type { Schema } from "./types";
import { getAppMetadata, getDefaultDatabasePath, pascalCase, camelCase } from "./utils";

export function genMcpServer(schema: Schema): string {
  const app = getAppMetadata(schema);
  const appConfig = {
    ...app,
    databasePath: getDefaultDatabasePath(app),
  };
  const entities = Object.keys(schema.tables);
  const tools: string[] = [];
  const handlers: string[] = [];

  for (const entity of entities) {
    const Entity = pascalCase(entity);
    const cols = schema.tables[entity];
    const ops = schema.operations[entity] || {};

    // Input properties for create/update
    const inputProps: Record<string, { type: string; description: string }> = {};
    const requiredProps: string[] = [];
    for (const [col, c] of Object.entries(cols)) {
      if (c.pk && c.auto) continue;
      inputProps[col] = {
        type: c.type === "integer" ? "number" : "string",
        description: col.replace(/_/g, " "),
      };
      if (c.required && c.default === null) requiredProps.push(col);
    }

    // List tool
    tools.push(`    {
      name: "list_${entity}s",
      description: "List all ${entity}s",
      inputSchema: { type: "object", properties: {} },
    }`);
    handlers.push(`      case "list_${entity}s":
        return { content: [{ type: "text", text: JSON.stringify(S.findAll${Entity}s(db), null, 2) }] };`);

    // Get tool
    tools.push(`    {
      name: "get_${entity}",
      description: "Get a ${entity} by ID",
      inputSchema: {
        type: "object",
        properties: { id: { type: "number", description: "${entity} ID" } },
        required: ["id"],
      },
    }`);
    handlers.push(`      case "get_${entity}":
        const ${entity} = S.find${Entity}ById(db, args.id as number);
        if (!${entity}) return { content: [{ type: "text", text: "Not found" }], isError: true };
        return { content: [{ type: "text", text: JSON.stringify(${entity}, null, 2) }] };`);

    // Create tool
    tools.push(`    {
      name: "create_${entity}",
      description: "Create a new ${entity}",
      inputSchema: {
        type: "object",
        properties: ${JSON.stringify(inputProps)},
        required: ${JSON.stringify(requiredProps)},
      },
    }`);
    handlers.push(`      case "create_${entity}":
        const create${Entity}Result = S.create${Entity}(db, args as T.${Entity}Input);
        if (!create${Entity}Result.ok) return { content: [{ type: "text", text: create${Entity}Result.error }], isError: true };
        return { content: [{ type: "text", text: JSON.stringify(create${Entity}Result.data) }] };`);

    // Delete tool
    tools.push(`    {
      name: "delete_${entity}",
      description: "Delete a ${entity}",
      inputSchema: {
        type: "object",
        properties: { id: { type: "number", description: "${entity} ID" } },
        required: ["id"],
      },
    }`);
    handlers.push(`      case "delete_${entity}":
        const delete${Entity}Result = S.delete${Entity}(db, args.id as number);
        if (!delete${Entity}Result.ok) return { content: [{ type: "text", text: delete${Entity}Result.error }], isError: true };
        return { content: [{ type: "text", text: "Deleted" }] };`);

    // Custom operations
    for (const opName of Object.keys(ops)) {
      const OpName = camelCase(opName);
      tools.push(`    {
      name: "${opName}_${entity}",
      description: "${opName.replace(/_/g, " ")} a ${entity}",
      inputSchema: {
        type: "object",
        properties: { id: { type: "number", description: "${entity} ID" } },
        required: ["id"],
      },
    }`);
      handlers.push(`      case "${opName}_${entity}":
        const ${OpName}${Entity}Result = S.${OpName}${Entity}(db, args.id as number);
        if (!${OpName}${Entity}Result.ok) return { content: [{ type: "text", text: ${OpName}${Entity}Result.error }], isError: true };
        return { content: [{ type: "text", text: JSON.stringify(${OpName}${Entity}Result.data) }] };`);
    }
  }

  return `// Generated by schema/codegen.ts — do not edit
// MCP Server for ${app.name}

import { Database } from "bun:sqlite";
import * as fs from "fs";
import * as S from "./services";
import * as T from "./types";

const APP_CONFIG = ${JSON.stringify(appConfig, null, 2)} as const;

const DB_PATH = process.env.DB_PATH || APP_CONFIG.databasePath;

const db = new Database(DB_PATH);
db.run("PRAGMA journal_mode = WAL");
db.run("PRAGMA foreign_keys = ON");

const sql = fs.readFileSync(new URL("./schema.sql", import.meta.url), "utf-8");
const statements = sql.split(/;\\s*\\n/).filter((s: string) => s.trim());
for (const stmt of statements) {
  if (stmt.trim()) db.run(stmt);
}

const SERVER_INFO = {
  name: APP_CONFIG.slug,
  version: APP_CONFIG.version,
};

const TOOLS = [
${tools.join(",\n")}
];

interface McpRequest {
  jsonrpc: "2.0";
  id: number | string;
  method: string;
  params?: Record<string, unknown>;
}

interface McpResponse {
  jsonrpc: "2.0";
  id: number | string;
  result?: unknown;
  error?: { code: number; message: string };
}

function handleRequest(req: McpRequest): McpResponse {
  switch (req.method) {
    case "initialize":
      return {
        jsonrpc: "2.0",
        id: req.id,
        result: {
          protocolVersion: "2025-03-26",
          serverInfo: SERVER_INFO,
          capabilities: { tools: {} },
        },
      };

    case "tools/list":
      return {
        jsonrpc: "2.0",
        id: req.id,
        result: { tools: TOOLS },
      };

    case "tools/call": {
      const { name, arguments: args = {} } = req.params as { name: string; arguments?: Record<string, unknown> };
      const result = callTool(name, args);
      return {
        jsonrpc: "2.0",
        id: req.id,
        result,
      };
    }

    default:
      return {
        jsonrpc: "2.0",
        id: req.id,
        error: { code: -32601, message: "Method not found" },
      };
  }
}

function callTool(name: string, args: Record<string, unknown>): { content: { type: string; text: string }[]; isError?: boolean } {
  switch (name) {
${handlers.join("\n")}
    default:
      return { content: [{ type: "text", text: "Unknown tool" }], isError: true };
  }
}

const MCP_PORT = parseInt(process.env.MCP_PORT || String(APP_CONFIG.defaultPorts.mcp), 10);

if (process.argv.includes("--http")) {
  // Streamable HTTP transport (MCP 2025-03-26)
  const sessions = new Map<string, boolean>();

  const CORS_HEADERS = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Mcp-Session-Id",
    "Access-Control-Expose-Headers": "Mcp-Session-Id",
  };

  Bun.serve({
    port: MCP_PORT,
    fetch(req) {
      const url = new URL(req.url);
      if (url.pathname !== "/mcp") {
        return new Response("Not found", { status: 404 });
      }

      if (req.method === "OPTIONS") {
        return new Response(null, { status: 204, headers: CORS_HEADERS });
      }

      if (req.method !== "POST") {
        return new Response("Method not allowed", { status: 405, headers: CORS_HEADERS });
      }

      return (async () => {
        const body = await req.json() as McpRequest;

        const headers: Record<string, string> = {
          "Content-Type": "application/json",
          ...CORS_HEADERS,
        };

        // JSON-RPC notifications have no id — acknowledge with 202
        if (body.id === undefined) {
          // Still validate session for non-initialize notifications
          if (body.method !== "initialize") {
            const sessionId = req.headers.get("Mcp-Session-Id");
            if (!sessionId || !sessions.has(sessionId)) {
              return new Response(null, { status: 400, headers: CORS_HEADERS });
            }
          }
          return new Response(null, { status: 202, headers: CORS_HEADERS });
        }

        if (body.method === "initialize") {
          const sessionId = crypto.randomUUID();
          sessions.set(sessionId, true);
          headers["Mcp-Session-Id"] = sessionId;
        } else {
          const sessionId = req.headers.get("Mcp-Session-Id");
          if (!sessionId || !sessions.has(sessionId)) {
            return new Response(JSON.stringify({
              jsonrpc: "2.0",
              id: body.id,
              error: { code: -32600, message: "Invalid or missing session ID" },
            }), { status: 400, headers: { "Content-Type": "application/json", ...CORS_HEADERS } });
          }
        }

        const res = handleRequest(body);
        return new Response(JSON.stringify(res), { headers });
      })();
    },
  });

  console.error(\`MCP HTTP server listening on http://localhost:\${MCP_PORT}/mcp\`);
} else {
  // Stdio transport
  async function main() {
    const decoder = new TextDecoder();
    let buffer = "";

    for await (const chunk of Bun.stdin.stream()) {
      buffer += decoder.decode(chunk);

      const lines = buffer.split("\\n");
      buffer = lines.pop() || "";

      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const req = JSON.parse(line) as McpRequest;
          const res = handleRequest(req);
          console.log(JSON.stringify(res));
        } catch (e) {
          console.log(JSON.stringify({
            jsonrpc: "2.0",
            id: null,
            error: { code: -32700, message: "Parse error" },
          }));
        }
      }
    }
  }

  main();
}
`;
}
