import type { Schema } from "./types";
import { getAppMetadata, getDefaultDatabasePath } from "./utils";

export function genRuntime(schema: Schema): string {
  const app = getAppMetadata(schema);
  const appConfig = {
    ...app,
    databasePath: getDefaultDatabasePath(app),
    seed: {
      applyFixturesByDefault: schema.seed?.applyFixturesByDefault ?? false,
    },
  };

  return `// Generated by schema/codegen.ts — do not edit

import { Database } from "bun:sqlite";
import * as fs from "fs";
import * as path from "path";
import * as S from "./services";

export const APP_CONFIG = ${JSON.stringify(appConfig, null, 2)} as const;

export const DB_PATH = process.env.DB_PATH || APP_CONFIG.databasePath;
export const MIGRATIONS_DIR = process.env.MIGRATIONS_DIR || new URL("./migrations", import.meta.url).pathname;
export const LOG_LEVEL = process.env.LOG_LEVEL || "info";
export const PRODUCTION = process.env.NODE_ENV === "production";
export const OPENB2C_APPLY_FIXTURES = process.env.OPENB2C_APPLY_FIXTURES;
export const APPLY_FIXTURES =
  OPENB2C_APPLY_FIXTURES === "true" ||
  (OPENB2C_APPLY_FIXTURES !== "false" && !PRODUCTION && APP_CONFIG.seed.applyFixturesByDefault);
export const REGISTRY_PRIVATE_KEY = process.env.REGISTRY_PRIVATE_KEY;  // hex-encoded Ed25519 private key
export const REGISTRY_PUBLIC_KEY = process.env.REGISTRY_PUBLIC_KEY;   // for verifying certs from external registry
export const USE_EXTERNAL_REGISTRY = !REGISTRY_PRIVATE_KEY && !!REGISTRY_PUBLIC_KEY;
export const REQUIRE_LOCAL_CERTIFICATE_REGISTRY = !USE_EXTERNAL_REGISTRY;

export interface Runtime {
  db: Database;
}

let runtime: Runtime | null = null;

// Structured logging
export function log(level: string, msg: string, data?: Record<string, unknown>) {
  if (level === "debug" && LOG_LEVEL !== "debug") return;
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  console.log(JSON.stringify(entry));
}

export function bootstrapRuntime(): Runtime {
  if (runtime) return runtime;

  const db = new Database(DB_PATH);
  db.run("PRAGMA journal_mode = WAL");
  db.run("PRAGMA foreign_keys = ON");

  const sql = fs.readFileSync(new URL("./schema.sql", import.meta.url), "utf-8");
  runSchemaMigrations(db, sql);
  runSeedData(db);

  runtime = { db };
  return runtime;
}

export function hashString(value: string): string {
  let hash = 2166136261;
  for (let i = 0; i < value.length; i++) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function sqlStatements(source: string): string[] {
  return source.split(/;\\s*\\n/).map((s: string) => s.trim()).filter(Boolean);
}

function ensureMigrationHistory(db: Database) {
  db.run(\`
    CREATE TABLE IF NOT EXISTS openb2c_migration (
      id TEXT PRIMARY KEY,
      checksum TEXT NOT NULL,
      description TEXT NOT NULL,
      applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  \`);
}

function hasUserSchema(db: Database): boolean {
  const row = db.query<{ name: string }, []>(\`
    SELECT name FROM sqlite_master
    WHERE type = 'table'
      AND name NOT LIKE 'sqlite_%'
      AND name != 'openb2c_migration'
    LIMIT 1
  \`).get();
  return !!row;
}

function migrationRow(db: Database, id: string): { checksum: string } | null {
  return db.query<{ checksum: string }, [string]>("SELECT checksum FROM openb2c_migration WHERE id = ?").get(id) || null;
}

function recordMigration(db: Database, id: string, checksum: string, description: string) {
  db.query("INSERT INTO openb2c_migration (id, checksum, description) VALUES (?, ?, ?)").run(id, checksum, description);
}

function applyMigration(db: Database, id: string, source: string, description: string) {
  const checksum = hashString(source);
  const existing = migrationRow(db, id);
  if (existing) {
    if (existing.checksum !== checksum) {
      throw new Error(\`Migration \${id} checksum changed after it was applied\`);
    }
    return;
  }
  const apply = db.transaction(() => {
    for (const stmt of sqlStatements(source)) db.run(stmt);
    recordMigration(db, id, checksum, description);
  });
  apply();
  log("info", "migration applied", { id, description });
}

function applySeedSql(db: Database, source: string, description: string) {
  const statements = sqlStatements(source);
  if (statements.length === 0) return;
  const apply = db.transaction(() => {
    for (const stmt of statements) db.run(stmt);
  });
  apply();
  log("info", "seed data applied", { description, statements: statements.length });
}

function seedFile(fileName: string): string | null {
  const file = new URL(\`./\${fileName}\`, import.meta.url);
  if (!fs.existsSync(file)) return null;
  const source = fs.readFileSync(file, "utf-8");
  return source.trim() ? source : null;
}

export function runSeedData(db: Database) {
  const referenceSeed = seedFile("seed.sql");
  if (referenceSeed) applySeedSql(db, referenceSeed, "reference seed data");

  const fixtureSeed = seedFile("fixtures.sql");
  if (fixtureSeed && APPLY_FIXTURES) applySeedSql(db, fixtureSeed, "fixture seed data");
}

function migrationFiles(): { id: string; path: string; source: string; checksum: string }[] {
  if (!fs.existsSync(MIGRATIONS_DIR)) return [];
  return fs.readdirSync(MIGRATIONS_DIR)
    .filter((file: string) => file.endsWith(".sql"))
    .sort()
    .map((file: string) => {
      const source = fs.readFileSync(path.join(MIGRATIONS_DIR, file), "utf-8");
      return { id: file.replace(/\\.sql$/, ""), path: file, source, checksum: hashString(source) };
    });
}

export function runSchemaMigrations(db: Database, schemaSql: string) {
  ensureMigrationHistory(db);
  const files = migrationFiles();
  if (!hasUserSchema(db)) {
    applyMigration(db, \`schema:\${hashString(schemaSql)}\`, schemaSql, "generated schema baseline");
    for (const file of files) {
      if (!migrationRow(db, file.id)) {
        recordMigration(db, file.id, file.checksum, \`included in fresh schema baseline: \${file.path}\`);
      }
    }
    return;
  }
  for (const file of files) {
    applyMigration(db, file.id, file.source, \`migration file: \${file.path}\`);
  }
  applyMigration(db, \`schema:\${hashString(schemaSql)}\`, schemaSql, "generated schema sync");
}

export async function initRegistryPublicKey(): Promise<string> {
  if (REGISTRY_PRIVATE_KEY) {
    const publicKey = await S.initRegistryKeys(REGISTRY_PRIVATE_KEY);
    log("info", "loaded registry keys");
    return publicKey;
  } else if (!REGISTRY_PUBLIC_KEY) {
    const publicKey = await S.initRegistryKeys();
    log("info", "generated ephemeral registry keys", { publicKey });
    return publicKey;
  } else {
    log("info", "using external registry");
    return REGISTRY_PUBLIC_KEY;
  }
}
`;
}
