import type { Schema } from "./types";
import { getAppMetadata, getDefaultDatabasePath, pascalCase, camelCase } from "./utils";

export function genRoutes(schema: Schema): string {
  const app = getAppMetadata(schema);
  const appConfig = {
    ...app,
    databasePath: getDefaultDatabasePath(app),
  };
  const entities = Object.keys(schema.tables);
  const routes: string[] = [];

  for (const entity of entities) {
    const Entity = pascalCase(entity);
    const ops = schema.operations[entity] || {};

    routes.push(`  // ${Entity}`);
    routes.push(`  { method: "GET", path: "/api/${entity}s", handler: (req, _, auth) => {
    const authz = S.authorizeCollection("${entity}", "read", auth);
    if (!authz.ok) return corsResponse(authz, { status: S.statusForResult(authz) });
    const url = new URL(req.url);
    const limit = parseInt(url.searchParams.get("limit") || "100");
    const offset = parseInt(url.searchParams.get("offset") || "0");
    const sort = url.searchParams.get("sort") || undefined;
    const order = url.searchParams.get("order") as "asc" | "desc" | undefined;
    const filter: Record<string, string> = {};
    for (const [k, v] of url.searchParams) {
      if (!["limit", "offset", "sort", "order"].includes(k)) filter[k] = v;
    }
    const items = S.findAll${Entity}s(db, { limit, offset, sort, order, filter: Object.keys(filter).length ? filter : undefined }, auth);
    const total = S.count${Entity}s(db, Object.keys(filter).length ? filter : undefined, auth);
    return corsResponse({ items: items.map(i => redact("${entity}", i)), total, limit, offset });
  }},`);
    routes.push(`  { method: "GET", path: "/api/${entity}s/:id", handler: (_, p, auth) => {
    const authz = S.authorizeCollection("${entity}", "read", auth);
    if (!authz.ok) return corsResponse(authz, { status: S.statusForResult(authz) });
    const r = S.find${Entity}ById(db, +p.id, auth);
    return r ? corsResponse(redact("${entity}", r)) : corsResponse({ error: "not found" }, { status: 404 });
  }},`);

    // Special handling for api_key creation - generate and hash key
    if (entity === "api_key") {
      routes.push(`  { method: "POST", path: "/api/${entity}s", handler: async (req, _, auth) => {
    const input = await req.json() as { name: string; user_id?: number; scopes?: string; expires_at?: string };
    const rawKey = S.generateApiKey();
    const keyHash = await S.hashApiKey(rawKey);
    const r = S.createApiKey(db, { ...input, key_hash: keyHash, key_prefix: rawKey.slice(0, 11) }, auth);
    if (!r.ok) return corsResponse(r, { status: S.statusForResult(r) });
    // Return raw key ONCE - it cannot be retrieved again
    return corsResponse({ id: r.data.id, key: rawKey, key_prefix: rawKey.slice(0, 11) }, { status: 201 });
  }},`);
    } else {
      routes.push(`  { method: "POST", path: "/api/${entity}s", handler: async (req, _, auth) => {
    const r = S.create${Entity}(db, await req.json(), auth);
    return r.ok ? corsResponse(r.data, { status: 201 }) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);
    }

    routes.push(`  { method: "PUT", path: "/api/${entity}s/:id", handler: async (req, p, auth) => {
    const r = S.update${Entity}(db, +p.id, await req.json(), auth);
    return r.ok ? corsResponse(r.data) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);
    routes.push(`  { method: "DELETE", path: "/api/${entity}s/:id", handler: (_, p, auth) => {
    const r = S.delete${Entity}(db, +p.id, auth);
    return r.ok ? corsResponse(r.data) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);

    // Custom operations
    for (const opName of Object.keys(ops)) {
      const OpName = camelCase(opName);
      routes.push(`  { method: "POST", path: "/api/${entity}s/:id/${opName.replace(/_/g, "-")}", handler: (_, p, auth) => {
    const r = S.${OpName}${Entity}(db, +p.id, auth);
    return r.ok ? corsResponse(r.data) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);
    }
    routes.push("");
  }

  return `// Generated by schema/codegen.ts — do not edit

import { Database } from "bun:sqlite";
import * as fs from "fs";
import * as S from "./services";
import * as T from "./types";

const APP_CONFIG = ${JSON.stringify(appConfig, null, 2)} as const;

const DB_PATH = process.env.DB_PATH || APP_CONFIG.databasePath;
const PORT = parseInt(process.env.PORT || String(APP_CONFIG.defaultPorts.server), 10);
const LOG_LEVEL = process.env.LOG_LEVEL || "info";
const AUTH_ENABLED = process.env.AUTH_ENABLED !== "false";  // enabled by default
const PRODUCTION = process.env.NODE_ENV === "production";
const REGISTRY_PRIVATE_KEY = process.env.REGISTRY_PRIVATE_KEY;  // hex-encoded Ed25519 private key
const REGISTRY_PUBLIC_KEY = process.env.REGISTRY_PUBLIC_KEY;   // for verifying certs from external registry

// Structured logging
function log(level: string, msg: string, data?: Record<string, unknown>) {
  if (level === "debug" && LOG_LEVEL !== "debug") return;
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  console.log(JSON.stringify(entry));
}

// Fields to exclude from API responses (sensitive data)
const REDACTED_FIELDS: Record<string, string[]> = {
  api_key: ["key_hash"],
};

function redact<T extends Record<string, unknown>>(entity: string, obj: T): T {
  const fields = REDACTED_FIELDS[entity];
  if (!fields) return obj;
  const result = { ...obj };
  for (const f of fields) delete (result as Record<string, unknown>)[f];
  return result;
}

const db = new Database(DB_PATH);
db.run("PRAGMA journal_mode = WAL");
db.run("PRAGMA foreign_keys = ON");

const sql = fs.readFileSync(new URL("./schema.sql", import.meta.url), "utf-8");
const statements = sql.split(/;\\s*\\n/).filter((s: string) => s.trim());
for (const stmt of statements) {
  if (stmt.trim()) db.run(stmt);
}

async function initRegistryPublicKey(): Promise<string> {
  if (REGISTRY_PRIVATE_KEY) {
    const publicKey = await S.initRegistryKeys(REGISTRY_PRIVATE_KEY);
    log("info", "loaded registry keys");
    return publicKey;
  } else if (!REGISTRY_PUBLIC_KEY) {
    const publicKey = await S.initRegistryKeys();
    log("info", "generated ephemeral registry keys", { publicKey });
    return publicKey;
  } else {
    log("info", "using external registry");
    return REGISTRY_PUBLIC_KEY;
  }
}

const registryPubKey = await initRegistryPublicKey();

type Handler = (req: Request, params: Record<string, string>, auth: T.AuthContext) => Response | Promise<Response>;

interface Route {
  method: string;
  path: string;
  handler: Handler;
}

const routes: Route[] = [
  // Identity endpoints (no auth required)
  { method: "GET", path: "/identity/public-key", handler: async () => {
    return corsResponse({ publicKey: registryPubKey });
  }},
  { method: "POST", path: "/identity/challenge", handler: async (req) => {
    const { email, publicKey } = await req.json() as { email: string; publicKey: string };
    if (!email || !publicKey) {
      return corsResponse({ error: "email and publicKey required", code: "invalid" }, { status: 400 });
    }
    const result = await S.createChallenge(db, email, publicKey);
    log("info", "identity challenge created", { email });
    // In production, code must be sent via email. In dev, return it for testing.
    if (PRODUCTION) {
      return corsResponse({ challengeId: result.challengeId, message: "verification code sent to email" });
    }
    return corsResponse({ challengeId: result.challengeId, code: result.code });
  }},
  { method: "POST", path: "/identity/verify", handler: async (req) => {
    const { challengeId, code, signature } = await req.json() as { challengeId: number; code: string; signature: string };
    const result = await S.verifyChallenge(db, challengeId, code, signature);
    if (!result.ok) {
      return corsResponse(result, { status: 400 });
    }
    return corsResponse({ certificate: result.data });
  }},

${routes.join("\n")}];

function matchRoute(method: string, path: string): { route: Route; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.method !== method) continue;
    const routeParts = route.path.split("/");
    const pathParts = path.split("/");
    if (routeParts.length !== pathParts.length) continue;

    const params: Record<string, string> = {};
    let match = true;
    for (let i = 0; i < routeParts.length; i++) {
      if (routeParts[i].startsWith(":")) {
        params[routeParts[i].slice(1)] = pathParts[i];
      } else if (routeParts[i] !== pathParts[i]) {
        match = false;
        break;
      }
    }
    if (match) return { route, params };
  }
  return null;
}

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, X-Certificate, X-Signature, X-Timestamp",
};

function corsResponse(body: unknown, init?: ResponseInit): Response {
  const res = Response.json(body, init);
  for (const [k, v] of Object.entries(CORS_HEADERS)) {
    res.headers.set(k, v);
  }
  return res;
}

export const server = Bun.serve({
  port: PORT,
  async fetch(req) {
    const start = performance.now();
    const url = new URL(req.url);
    let authContext: T.AuthContext = AUTH_ENABLED ? T.ANONYMOUS_AUTH_CONTEXT : T.SYSTEM_AUTH_CONTEXT;

    // CORS preflight
    if (req.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    // Health check (no auth)
    if (url.pathname === "/health") {
      return corsResponse({ status: "ok", app: APP_CONFIG.slug, db: DB_PATH, auth: AUTH_ENABLED });
    }

    // Skip auth for identity endpoints
    if (url.pathname.startsWith("/identity/")) {
      // handled by routes
    }
    // Auth check for API endpoints. Missing credentials remain anonymous so
    // per-route authorization can distinguish public endpoints from protected ones.
    else if (AUTH_ENABLED && url.pathname.startsWith("/api/")) {
      const authHeader = req.headers.get("Authorization");
      const certHeader = req.headers.get("X-Certificate");
      const sigHeader = req.headers.get("X-Signature");
      const tsHeader = req.headers.get("X-Timestamp");

      if (certHeader && sigHeader && tsHeader) {
        // Certificate-based auth
        try {
          const cert = JSON.parse(certHeader) as T.Certificate;
          const identity = await S.verifyRequest(cert, registryPubKey, req.method, url.pathname, tsHeader, sigHeader);
          if (!identity) {
            return corsResponse({ error: "invalid certificate or signature", code: "invalid" }, { status: 401 });
          }
          // Ensure user record exists for this identity
          const userId = S.ensureUser(db, identity.email);
          const userAttrs = S.getUserAuthAttributes(db, userId);
          authContext = {
            kind: "identity",
            provider: "certificate",
            subject: \`user:\${userId}\`,
            userId,
            email: identity.email,
            publicKey: identity.publicKey,
            certificate: identity.certificate,
            principals: userAttrs.principals.length ? userAttrs.principals : ["user"],
            roles: userAttrs.roles,
            scopes: ["read", "write"],
            claims: {
              ...userAttrs.claims,
              email: identity.email,
              publicKey: identity.publicKey,
            },
          };
          log("debug", "authenticated", { email: identity.email, userId });
        } catch {
          return corsResponse({ error: "invalid certificate format", code: "invalid" }, { status: 401 });
        }
      } else if (authHeader?.startsWith("Bearer ")) {
        // API key auth (for services/integrations)
        const key = authHeader.slice(7);
        const auth = await S.verifyApiKey(db, key);
        if (!auth) {
          return corsResponse({ error: "invalid api key", code: "invalid" }, { status: 401 });
        }
        authContext = auth;
      }
    }

    const result = matchRoute(req.method, url.pathname);
    if (!result) {
      log("info", "not found", { method: req.method, path: url.pathname });
      return corsResponse({ error: "not found" }, { status: 404 });
    }

    try {
      const res = await result.route.handler(req, result.params, authContext);
      const ms = (performance.now() - start).toFixed(1);
      log("info", "request", { method: req.method, path: url.pathname, status: res.status, ms });
      return res;
    } catch (err) {
      const ms = (performance.now() - start).toFixed(1);
      log("error", "request failed", { method: req.method, path: url.pathname, error: String(err), ms });
      return corsResponse({ error: "internal error" }, { status: 500 });
    }
  },
});

log("info", "server started", { app: APP_CONFIG.slug, port: server.port, db: DB_PATH, auth: AUTH_ENABLED });
`;
}
