import type { Schema } from "./types";
import { getAppMetadata, getDefaultDatabasePath, pascalCase, camelCase } from "./utils";

const CRUD_ACTIONS = new Set(["read", "create", "update", "delete"]);

export function genRoutes(schema: Schema): string {
  const app = getAppMetadata(schema);
  const appConfig = {
    ...app,
    databasePath: getDefaultDatabasePath(app),
  };
  const entities = Object.keys(schema.tables);
  const routes: string[] = [];

  for (const entity of entities) {
    const Entity = pascalCase(entity);
    const ops = schema.operations[entity] || {};

    routes.push(`  // ${Entity}`);
    routes.push(`  { method: "GET", path: "/api/${entity}s", handler: (req, _, auth) => {
    const authz = S.authorizeCollection("${entity}", "read", auth);
    if (!authz.ok) return corsResponse(authz, { status: S.statusForResult(authz) });
    const url = new URL(req.url);
    const limit = clampLimit(url.searchParams.get("limit"));
    const offset = clampOffset(url.searchParams.get("offset"));
    const sort = url.searchParams.get("sort") || undefined;
    const order = url.searchParams.get("order") as "asc" | "desc" | undefined;
    const filter: Record<string, string> = {};
    for (const [k, v] of url.searchParams) {
      if (!["limit", "offset", "sort", "order"].includes(k)) filter[k] = v;
    }
    const items = S.findAll${Entity}s(db, { limit, offset, sort, order, filter: Object.keys(filter).length ? filter : undefined }, auth);
    const total = S.count${Entity}s(db, Object.keys(filter).length ? filter : undefined, auth);
    return corsResponse({ items: items.map(i => redact("${entity}", i)), total, limit, offset });
  }},`);
    routes.push(`  { method: "GET", path: "/api/${entity}s/:id", handler: (_, p, auth) => {
    const authz = S.authorizeCollection("${entity}", "read", auth);
    if (!authz.ok) return corsResponse(authz, { status: S.statusForResult(authz) });
    const r = S.find${Entity}ById(db, +p.id, auth);
    return r ? corsResponse(redact("${entity}", r)) : corsResponse({ error: "not found" }, { status: 404 });
  }},`);

    // Special handling for api_key creation - generate and hash key
    if (entity === "api_key") {
      routes.push(`  { method: "POST", path: "/api/${entity}s", handler: async (req, _, auth, signal) => {
    const input = await readJson<{ name: string; user_id?: number; scopes?: string; expires_at?: string }>(req, signal);
    if (!input.ok) return corsResponse(input, { status: S.statusForResult(input) });
    const rawKey = S.generateApiKey();
    const keyHash = await S.hashApiKey(rawKey);
    const r = S.createApiKey(db, { ...input.data, key_hash: keyHash, key_prefix: rawKey.slice(0, 11) }, auth);
    if (!r.ok) return corsResponse(r, { status: S.statusForResult(r) });
    // Return raw key ONCE - it cannot be retrieved again
    return corsResponse({ id: r.data.id, key: rawKey, key_prefix: rawKey.slice(0, 11) }, { status: 201 });
  }},`);
    } else {
      routes.push(`  { method: "POST", path: "/api/${entity}s", handler: async (req, _, auth, signal) => {
    const input = await readJson<T.${Entity}Input>(req, signal);
    if (!input.ok) return corsResponse(input, { status: S.statusForResult(input) });
    const r = S.create${Entity}(db, input.data, auth);
    return r.ok ? corsResponse(r.data, { status: 201 }) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);
    }

    routes.push(`  { method: "PUT", path: "/api/${entity}s/:id", handler: async (req, p, auth, signal) => {
    const input = await readJson<Partial<T.${Entity}Input>>(req, signal);
    if (!input.ok) return corsResponse(input, { status: S.statusForResult(input) });
    const r = S.update${Entity}(db, +p.id, input.data, auth);
    return r.ok ? corsResponse(r.data) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);
    routes.push(`  { method: "DELETE", path: "/api/${entity}s/:id", handler: (_, p, auth) => {
    const r = S.delete${Entity}(db, +p.id, auth);
    return r.ok ? corsResponse(r.data) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);

    // Custom operations
    for (const opName of Object.keys(ops).filter(op => !CRUD_ACTIONS.has(op))) {
      const OpName = camelCase(opName);
      routes.push(`  { method: "POST", path: "/api/${entity}s/:id/${opName.replace(/_/g, "-")}", handler: (_, p, auth) => {
    const r = S.${OpName}${Entity}(db, +p.id, auth);
    return r.ok ? corsResponse(r.data) : corsResponse(r, { status: S.statusForResult(r) });
  }},`);
    }
    routes.push("");
  }

  return `// Generated by schema/codegen.ts — do not edit

import { Database } from "bun:sqlite";
import * as fs from "fs";
import * as S from "./services";
import * as T from "./types";

const APP_CONFIG = ${JSON.stringify(appConfig, null, 2)} as const;

const DB_PATH = process.env.DB_PATH || APP_CONFIG.databasePath;
const PORT = parseInt(process.env.PORT || String(APP_CONFIG.defaultPorts.server), 10);
const LOG_LEVEL = process.env.LOG_LEVEL || "info";
const MAX_REQUEST_BODY_BYTES = parseInt(process.env.MAX_REQUEST_BODY_BYTES || "1048576", 10);
const MAX_PAGE_LIMIT = parseInt(process.env.MAX_PAGE_LIMIT || "1000", 10);
const ROUTE_TIMEOUT_MS = Math.max(parseInt(process.env.ROUTE_TIMEOUT_MS || "30000", 10) || 30000, 1);
const CORS_ORIGINS = (process.env.CORS_ORIGINS || "*").split(",").map(o => o.trim()).filter(Boolean);
const CORS_ALLOW_CREDENTIALS = process.env.CORS_ALLOW_CREDENTIALS === "true";
const AUTH_ENABLED = process.env.AUTH_ENABLED !== "false";  // enabled by default
const PRODUCTION = process.env.NODE_ENV === "production";
const REGISTRY_PRIVATE_KEY = process.env.REGISTRY_PRIVATE_KEY;  // hex-encoded Ed25519 private key
const REGISTRY_PUBLIC_KEY = process.env.REGISTRY_PUBLIC_KEY;   // for verifying certs from external registry
const USE_EXTERNAL_REGISTRY = !REGISTRY_PRIVATE_KEY && !!REGISTRY_PUBLIC_KEY;
const REQUIRE_LOCAL_CERTIFICATE_REGISTRY = !USE_EXTERNAL_REGISTRY;

// Structured logging
function log(level: string, msg: string, data?: Record<string, unknown>) {
  if (level === "debug" && LOG_LEVEL !== "debug") return;
  const entry = { ts: new Date().toISOString(), level, msg, ...data };
  console.log(JSON.stringify(entry));
}

// Fields to exclude from API responses (sensitive data)
const REDACTED_FIELDS: Record<string, string[]> = {
  api_key: ["key_hash"],
};

function redact<T extends Record<string, unknown>>(entity: string, obj: T): T {
  const fields = REDACTED_FIELDS[entity];
  if (!fields) return obj;
  const result = { ...obj };
  for (const f of fields) delete (result as Record<string, unknown>)[f];
  return result;
}

function clientIp(req: Request): string {
  const forwarded = req.headers.get("x-forwarded-for");
  if (forwarded) return forwarded.split(",")[0]?.trim() || "unknown";
  return req.headers.get("x-real-ip") || req.headers.get("cf-connecting-ip") || "unknown";
}

class RouteTimeoutError extends Error {
  constructor() {
    super("request timed out");
  }
}

function timeoutResult(): S.Result<never> {
  return { ok: false, error: "request timed out", code: "timeout" };
}

async function readRequestBody(req: Request, signal: AbortSignal): Promise<S.Result<string>> {
  if (!req.body) return { ok: true, data: "" };
  if (signal.aborted) return timeoutResult();

  const reader = req.body.getReader();
  const decoder = new TextDecoder();
  let body = "";
  let bytes = 0;
  let abortListener: (() => void) | undefined;
  const aborted = new Promise<never>((_, reject) => {
    abortListener = () => reject(new RouteTimeoutError());
    signal.addEventListener("abort", abortListener, { once: true });
  });

  try {
    while (true) {
      const { done, value } = await Promise.race([reader.read(), aborted]);
      if (done) break;
      if (!value) continue;
      bytes += value.byteLength;
      if (bytes > MAX_REQUEST_BODY_BYTES) {
        await reader.cancel();
        return { ok: false, error: "request body too large", code: "payload_too_large" };
      }
      body += decoder.decode(value, { stream: true });
    }
    body += decoder.decode();
    return { ok: true, data: body };
  } catch (err) {
    if (err instanceof RouteTimeoutError) {
      await reader.cancel().catch(() => {});
      return timeoutResult();
    }
    throw err;
  } finally {
    if (abortListener) signal.removeEventListener("abort", abortListener);
  }
}

async function readJson<T>(req: Request, signal: AbortSignal): Promise<S.Result<T>> {
  const contentType = req.headers.get("content-type") || "";
  const mediaType = contentType.split(";")[0]?.trim().toLowerCase();
  if (mediaType !== "application/json" && !mediaType?.endsWith("+json")) {
    return { ok: false, error: "content-type must be application/json", code: "unsupported_media_type" };
  }

  const contentLength = req.headers.get("content-length");
  if (contentLength && Number(contentLength) > MAX_REQUEST_BODY_BYTES) {
    return { ok: false, error: "request body too large", code: "payload_too_large" };
  }

  const body = await readRequestBody(req, signal);
  if (!body.ok) return body;

  try {
    return { ok: true, data: JSON.parse(body.data) as T };
  } catch {
    return { ok: false, error: "malformed JSON", code: "invalid" };
  }
}

function parseIntegerParam(value: string | null, fallback: number): number {
  if (value === null) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function clampLimit(value: string | null): number {
  return Math.min(Math.max(parseIntegerParam(value, 100), 1), MAX_PAGE_LIMIT);
}

function clampOffset(value: string | null): number {
  return Math.max(parseIntegerParam(value, 0), 0);
}

const db = new Database(DB_PATH);
db.run("PRAGMA journal_mode = WAL");
db.run("PRAGMA foreign_keys = ON");

const sql = fs.readFileSync(new URL("./schema.sql", import.meta.url), "utf-8");
const statements = sql.split(/;\\s*\\n/).filter((s: string) => s.trim());
for (const stmt of statements) {
  if (stmt.trim()) db.run(stmt);
}

async function initRegistryPublicKey(): Promise<string> {
  if (REGISTRY_PRIVATE_KEY) {
    const publicKey = await S.initRegistryKeys(REGISTRY_PRIVATE_KEY);
    log("info", "loaded registry keys");
    return publicKey;
  } else if (!REGISTRY_PUBLIC_KEY) {
    const publicKey = await S.initRegistryKeys();
    log("info", "generated ephemeral registry keys", { publicKey });
    return publicKey;
  } else {
    log("info", "using external registry");
    return REGISTRY_PUBLIC_KEY;
  }
}

const registryPubKey = await initRegistryPublicKey();

type Handler = (req: Request, params: Record<string, string>, auth: T.AuthContext, signal: AbortSignal) => Response | Promise<Response>;

interface Route {
  method: string;
  path: string;
  handler: Handler;
}

const routes: Route[] = [
  // Identity endpoints (no auth required)
  { method: "GET", path: "/identity/public-key", handler: async () => {
    return corsResponse({ publicKey: registryPubKey });
  }},
  { method: "POST", path: "/identity/challenge", handler: async (req, _, __, signal) => {
    const input = await readJson<{ email: string; publicKey: string }>(req, signal);
    if (!input.ok) return corsResponse(input, { status: S.statusForResult(input) });
    const { email, publicKey } = input.data;
    if (!email || !publicKey) {
      return corsResponse({ error: "email and publicKey required", code: "invalid" }, { status: 400 });
    }
    const result = await S.createChallenge(db, email, publicKey, clientIp(req));
    if (!result.ok) {
      return corsResponse(result, { status: S.statusForResult(result) });
    }
    log("info", "identity challenge created", { email });
    // In production, code must be sent via email. In dev, return it for testing.
    if (PRODUCTION) {
      return corsResponse({ challengeId: result.data.challengeId, message: "verification code sent to email" });
    }
    return corsResponse({ challengeId: result.data.challengeId, code: result.data.code });
  }},
  { method: "POST", path: "/identity/verify", handler: async (req, _, __, signal) => {
    const input = await readJson<{ challengeId: number; code: string; signature: string }>(req, signal);
    if (!input.ok) return corsResponse(input, { status: S.statusForResult(input) });
    const { challengeId, code, signature } = input.data;
    const result = await S.verifyChallenge(db, challengeId, code, signature);
    if (!result.ok) {
      return corsResponse(result, { status: S.statusForResult(result) });
    }
    return corsResponse({ certificate: result.data });
  }},

${routes.join("\n")}];

function matchRoute(method: string, path: string): { route: Route; params: Record<string, string> } | null {
  for (const route of routes) {
    if (route.method !== method) continue;
    const routeParts = route.path.split("/");
    const pathParts = path.split("/");
    if (routeParts.length !== pathParts.length) continue;

    const params: Record<string, string> = {};
    let match = true;
    for (let i = 0; i < routeParts.length; i++) {
      if (routeParts[i].startsWith(":")) {
        params[routeParts[i].slice(1)] = pathParts[i];
      } else if (routeParts[i] !== pathParts[i]) {
        match = false;
        break;
      }
    }
    if (match) return { route, params };
  }
  return null;
}

const CORS_ALLOW_METHODS = "GET, POST, PUT, DELETE, OPTIONS";
const CORS_ALLOW_HEADERS = "Content-Type, Authorization, X-Certificate, X-Signature, X-Timestamp";

function corsResponse(body: unknown, init?: ResponseInit): Response {
  return Response.json(body, init);
}

function allowedCorsOrigin(req: Request): string | null {
  const origin = req.headers.get("origin");
  if (CORS_ORIGINS.includes("*")) {
    return CORS_ALLOW_CREDENTIALS ? origin : "*";
  }
  return origin && CORS_ORIGINS.includes(origin) ? origin : null;
}

function corsHeaders(req: Request): Headers {
  const headers = new Headers();
  const origin = allowedCorsOrigin(req);
  if (origin) headers.set("Access-Control-Allow-Origin", origin);
  if (origin && CORS_ALLOW_CREDENTIALS && origin !== "*") {
    headers.set("Access-Control-Allow-Credentials", "true");
  }
  headers.set("Access-Control-Allow-Methods", CORS_ALLOW_METHODS);
  headers.set("Access-Control-Allow-Headers", CORS_ALLOW_HEADERS);
  headers.set("Vary", "Origin");
  return headers;
}

function applyCors(req: Request, res: Response): Response {
  for (const [k, v] of corsHeaders(req)) {
    res.headers.set(k, v);
  }
  return res;
}

function response(req: Request, body: unknown, init?: ResponseInit): Response {
  return applyCors(req, corsResponse(body, init));
}

function preflightResponse(req: Request): Response {
  if (req.headers.has("origin") && !allowedCorsOrigin(req)) {
    return response(req, { error: "origin not allowed", code: "forbidden" }, { status: 403 });
  }
  return new Response(null, { status: 204, headers: corsHeaders(req) });
}

async function runRouteWithTimeout(handler: (signal: AbortSignal) => Response | Promise<Response>): Promise<Response> {
  const controller = new AbortController();
  let timeout: ReturnType<typeof setTimeout> | undefined;
  const route = Promise.resolve().then(() => handler(controller.signal));
  const timedOut = new Promise<Response>((resolve) => {
    timeout = setTimeout(() => {
      controller.abort();
      resolve(corsResponse(timeoutResult(), { status: 504 }));
    }, ROUTE_TIMEOUT_MS);
  });

  try {
    return await Promise.race([route, timedOut]);
  } finally {
    if (timeout) clearTimeout(timeout);
  }
}

export const server = Bun.serve({
  port: PORT,
  async fetch(req) {
    const start = performance.now();
    const url = new URL(req.url);
    let authContext: T.AuthContext = AUTH_ENABLED ? T.ANONYMOUS_AUTH_CONTEXT : T.SYSTEM_AUTH_CONTEXT;

    // CORS preflight
    if (req.method === "OPTIONS") {
      return preflightResponse(req);
    }

    // Health check (no auth)
    if (url.pathname === "/health") {
      return response(req, { status: "ok", app: APP_CONFIG.slug, db: DB_PATH, auth: AUTH_ENABLED });
    }

    // Skip auth for identity endpoints
    if (url.pathname.startsWith("/identity/")) {
      // handled by routes
    }
    // Auth check for API endpoints. Missing credentials remain anonymous so
    // per-route authorization can distinguish public endpoints from protected ones.
    else if (AUTH_ENABLED && url.pathname.startsWith("/api/")) {
      const authHeader = req.headers.get("Authorization");
      const certHeader = req.headers.get("X-Certificate");
      const sigHeader = req.headers.get("X-Signature");
      const tsHeader = req.headers.get("X-Timestamp");

      if (certHeader && sigHeader && tsHeader) {
        // Certificate-based auth
        try {
          const cert = JSON.parse(certHeader) as T.Certificate;
          const identity = await S.verifyRequest(db, cert, registryPubKey, REQUIRE_LOCAL_CERTIFICATE_REGISTRY, req.method, url.pathname, tsHeader, sigHeader);
          if (!identity) {
            return response(req, { error: "invalid certificate or signature", code: "invalid" }, { status: 401 });
          }
          // Ensure user record exists for this identity
          const userId = S.ensureUser(db, identity.email);
          authContext = {
            userId,
            scopes: [...S.SELF_SERVICE_SCOPES],
          };
          log("debug", "authenticated", { email: identity.email, userId });
        } catch {
          return response(req, { error: "invalid certificate format", code: "invalid" }, { status: 401 });
        }
      } else if (authHeader?.startsWith("Bearer ")) {
        // API key auth (for services/integrations)
        const key = authHeader.slice(7);
        const auth = await S.verifyApiKey(db, key);
        if (!auth) {
          return response(req, { error: "invalid api key", code: "invalid" }, { status: 401 });
        }
        authContext = auth;
      }
    }

    const result = matchRoute(req.method, url.pathname);
    if (!result) {
      log("info", "not found", { method: req.method, path: url.pathname });
      return response(req, { error: "not found" }, { status: 404 });
    }

    try {
      const res = await runRouteWithTimeout((signal) => result.route.handler(req, result.params, authContext, signal));
      const ms = (performance.now() - start).toFixed(1);
      log("info", "request", { method: req.method, path: url.pathname, status: res.status, ms });
      return applyCors(req, res);
    } catch (err) {
      const ms = (performance.now() - start).toFixed(1);
      log("error", "request failed", { method: req.method, path: url.pathname, error: String(err), ms });
      return response(req, { error: "internal error" }, { status: 500 });
    }
  },
});

log("info", "server started", { app: APP_CONFIG.slug, port: server.port, db: DB_PATH, auth: AUTH_ENABLED });
`;
}
