import type { Column, Tables } from "./types";
import { pascalCase, TS_TYPE_MAP } from "./utils";

export function tsType(sqliteType: string): string {
  return TS_TYPE_MAP[sqliteType] ?? "unknown";
}

export function genRowInterface(table: string, cols: Record<string, Column>): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    const ts = tsType(c.type);
    const nullable = !c.pk && !c.required ? " | null" : "";
    fields.push(`  ${col}: ${ts}${nullable};`);
  }
  return `export interface ${name} {\n${fields.join("\n")}\n}`;
}

export function genInputInterface(table: string, cols: Record<string, Column>): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    if (c.pk && c.auto) continue;
    const ts = tsType(c.type);
    const opt = c.required ? "" : "?";
    fields.push(`  ${col}${opt}: ${ts};`);
  }
  return `export interface ${name}Input {\n${fields.join("\n")}\n}`;
}

export function genTypes(tables: Tables): string {
  const chunks: string[] = ["// Generated by schema/codegen.ts — do not edit\n"];
  for (const [table, cols] of Object.entries(tables)) {
    chunks.push(genRowInterface(table, cols));
    chunks.push(genInputInterface(table, cols));
  }
  return chunks.join("\n\n") + "\n";
}
