import type { Column, Tables } from "./types";
import { pascalCase, TS_TYPE_MAP } from "./utils";

const AUTH_TYPES = `export interface Certificate {
  email: string;
  publicKey: string;
  issuedAt: string;
  expiresAt: string;
  signature: string;
}

export const PLATFORM_PRINCIPALS = [
  "anonymous",
  "user",
  "customer",
  "staff",
  "admin",
  "service",
  "owner",
] as const;

export type PlatformPrincipal = typeof PLATFORM_PRINCIPALS[number];

export const AUTHENTICATED_PLATFORM_PRINCIPALS: PlatformPrincipal[] = [
  "user",
  "customer",
  "staff",
  "admin",
  "service",
];

// owner is resolved by authorization policy against a specific record.
export const POLICY_ONLY_PLATFORM_PRINCIPALS: PlatformPrincipal[] = ["owner"];

export type AuthProvider = "anonymous" | "api_key" | "certificate" | "system";
export type DomainRole = string;
export type PermissionScope = string;

export interface BaseAuthContext {
  provider: AuthProvider;
  subject: string | null;
  userId: number | null;
  principals: PlatformPrincipal[];
  roles: DomainRole[];
  scopes: PermissionScope[];
  claims: Record<string, unknown>;
}

export interface AnonymousAuthContext extends BaseAuthContext {
  kind: "anonymous";
  provider: "anonymous";
  subject: null;
  userId: null;
  principals: ["anonymous"];
}

export interface ApiKeyAuthContext extends BaseAuthContext {
  kind: "api_key";
  provider: "api_key";
  keyId: number;
  userId: number | null;
}

export interface IdentityAuthContext extends BaseAuthContext {
  kind: "identity";
  provider: "certificate";
  subject: string;
  userId: number;
  email: string;
  publicKey: string;
  certificate: Certificate;
}

export interface SystemAuthContext extends BaseAuthContext {
  kind: "system";
  provider: "system";
  subject: "system";
  userId: null;
  principals: ["service", "staff", "admin"];
}

export type AuthContext = AnonymousAuthContext | ApiKeyAuthContext | IdentityAuthContext | SystemAuthContext;

export const ANONYMOUS_AUTH_CONTEXT: AnonymousAuthContext = {
  kind: "anonymous",
  provider: "anonymous",
  subject: null,
  userId: null,
  principals: ["anonymous"],
  roles: [],
  scopes: [],
  claims: {},
};

export const SYSTEM_AUTH_CONTEXT: SystemAuthContext = {
  kind: "system",
  provider: "system",
  subject: "system",
  userId: null,
  principals: ["service", "staff", "admin"],
  roles: ["system"],
  scopes: ["*"],
  claims: { system: true },
};

export interface AuthorizationRule {
  principals?: PlatformPrincipal[];
  roles?: DomainRole[];
  scopes?: PermissionScope[];
  owner?: boolean;
  ownerFields?: string[];
}

export interface ActionAuthorizationPolicy {
  allow?: AuthorizationRule[];
}

export interface EntityAuthorizationPolicy {
  ownerFields?: string[];
  read?: ActionAuthorizationPolicy;
  create?: ActionAuthorizationPolicy;
  update?: ActionAuthorizationPolicy;
  delete?: ActionAuthorizationPolicy;
  operations?: Record<string, ActionAuthorizationPolicy>;
}`;

export function tsType(sqliteType: string): string {
  return TS_TYPE_MAP[sqliteType] ?? "unknown";
}

export function genRowInterface(table: string, cols: Record<string, Column>): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    const ts = tsType(c.type);
    const nullable = !c.pk && !c.required ? " | null" : "";
    fields.push(`  ${col}: ${ts}${nullable};`);
  }
  return `export interface ${name} {\n${fields.join("\n")}\n}`;
}

export function genInputInterface(table: string, cols: Record<string, Column>): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    if (c.pk && c.auto) continue;
    const ts = tsType(c.type);
    const opt = c.required ? "" : "?";
    fields.push(`  ${col}${opt}: ${ts};`);
  }
  return `export interface ${name}Input {\n${fields.join("\n")}\n}`;
}

export function genTypes(tables: Tables): string {
  const chunks: string[] = ["// Generated by schema/codegen.ts — do not edit\n", AUTH_TYPES];
  for (const [table, cols] of Object.entries(tables)) {
    chunks.push(genRowInterface(table, cols));
    chunks.push(genInputInterface(table, cols));
  }
  return chunks.join("\n\n") + "\n";
}
