import type { Column, DerivedField, DerivedFields, Operations, Tables } from "./types";
import { pascalCase, TS_TYPE_MAP } from "./utils";

const AUTH_TYPES = `export interface Certificate {
  email: string;
  publicKey: string;
  issuedAt: string;
  expiresAt: string;
  signature: string;
}

export type PermissionScope = string;

export interface AuthContext {
  userId: number | null;
  scopes: PermissionScope[];
}

export const ANONYMOUS_AUTH_CONTEXT: AuthContext = {
  userId: null,
  scopes: [],
};

export const SYSTEM_AUTH_CONTEXT: AuthContext = {
  userId: null,
  scopes: ["*"],
};

export interface FieldRef {
  table: string;
  field: string;
  references: string | null;
}

export interface Relationship {
  field: FieldRef;
}

export interface OperationPolicy {
  scope: PermissionScope;
  public: boolean;
  relationships: Relationship[];
}`;

export function tsType(sqliteType: string): string {
  return TS_TYPE_MAP[sqliteType] ?? "unknown";
}

export function genRowInterface(table: string, cols: Record<string, Column>, derived: Record<string, DerivedField> = {}): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    const ts = tsType(c.type);
    const nullable = !c.pk && !c.required ? " | null" : "";
    fields.push(`  ${col}: ${ts}${nullable};`);
  }
  for (const [field, derivedField] of Object.entries(derived)) {
    fields.push(`  ${field}: ${tsType(derivedField.type)};`);
  }
  return `export interface ${name} {\n${fields.join("\n")}\n}`;
}

function createRelationshipFields(table: string, operations?: Operations): Set<string> {
  const fields = new Set<string>();
  for (const rel of operations?.[table]?.create?.relationships ?? []) {
    if (rel.field.table === table) fields.add(rel.field.field);
  }
  return fields;
}

export function genInputInterface(
  table: string,
  cols: Record<string, Column>,
  optionalCreateFields: ReadonlySet<string> = new Set()
): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    if (c.pk && c.auto) continue;
    const ts = tsType(c.type);
    const opt = c.required && !optionalCreateFields.has(col) ? "" : "?";
    fields.push(`  ${col}${opt}: ${ts};`);
  }
  return `export interface ${name}Input {\n${fields.join("\n")}\n}`;
}

export function genTypes(tables: Tables, operations?: Operations, derived?: DerivedFields): string {
  const chunks: string[] = ["// Generated by schema/codegen.ts — do not edit\n", AUTH_TYPES];
  for (const [table, cols] of Object.entries(tables)) {
    chunks.push(genRowInterface(table, cols, derived?.[table] || {}));
    chunks.push(genInputInterface(table, cols, createRelationshipFields(table, operations)));
  }
  return chunks.join("\n\n") + "\n";
}
