/**
 * Generates SQLite schema and TypeScript types from Nix schema JSON.
 *
 * Usage: nix eval --json -f schema/default.nix | bun schema/codegen.ts
 * Output: src/generated/schema.sql, src/generated/types.ts
 */

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

interface Column {
  type: string;
  pk: boolean;
  auto: boolean;
  required: boolean;
  unique: boolean;
  default: string | null;
  references: string | null;
}

type Schema = Record<string, Record<string, Column>>;

const tsMap: Record<string, string> = {
  integer: "number",
  text: "string",
  real: "number",
  blob: "Uint8Array",
};

function pascalCase(s: string): string {
  return s.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
}

function genSQL(tables: Schema): string {
  const stmts: string[] = [];

  for (const [table, cols] of Object.entries(tables)) {
    const defs: string[] = [];
    for (const [col, c] of Object.entries(cols)) {
      const parts = [col, c.type.toUpperCase()];
      if (c.pk) parts.push("PRIMARY KEY");
      if (c.auto) parts.push("AUTOINCREMENT");
      if (c.required && !c.pk) parts.push("NOT NULL");
      if (c.unique) parts.push("UNIQUE");
      if (c.default !== null) parts.push(`DEFAULT ${c.default}`);
      if (c.references !== null) parts.push(`REFERENCES ${c.references}`);
      defs.push("    " + parts.join(" "));
    }
    stmts.push(
      `CREATE TABLE IF NOT EXISTS ${table} (\n${defs.join(",\n")}\n);`,
    );
  }

  return stmts.join("\n\n") + "\n";
}

function genTypes(tables: Schema): string {
  const chunks: string[] = ["// Generated by schema/codegen.ts — do not edit\n"];

  for (const [table, cols] of Object.entries(tables)) {
    const name = pascalCase(table);

    // Row type (all fields, nullable where not required/pk)
    const rowFields: string[] = [];
    for (const [col, c] of Object.entries(cols)) {
      const ts = tsMap[c.type] ?? "unknown";
      const nullable = !c.pk && !c.required ? ` | null` : "";
      rowFields.push(`  ${col}: ${ts}${nullable};`);
    }
    chunks.push(`export interface ${name} {\n${rowFields.join("\n")}\n}`);

    // Input type (omit auto-pk, optional where not required)
    const inputFields: string[] = [];
    for (const [col, c] of Object.entries(cols)) {
      if (c.pk && c.auto) continue;
      const ts = tsMap[c.type] ?? "unknown";
      const opt = c.required ? "" : "?";
      inputFields.push(`  ${col}${opt}: ${ts};`);
    }
    chunks.push(
      `export interface ${name}Input {\n${inputFields.join("\n")}\n}`,
    );
  }

  return chunks.join("\n\n") + "\n";
}

// Read JSON from stdin
const input = await Bun.stdin.text();
const schema: Schema = JSON.parse(input);

const outDir = join(import.meta.dir, "..", "src", "generated");
mkdirSync(outDir, { recursive: true });

writeFileSync(join(outDir, "schema.sql"), genSQL(schema));
writeFileSync(join(outDir, "types.ts"), genTypes(schema));

console.log("wrote src/generated/schema.sql");
console.log("wrote src/generated/types.ts");
