/**
 * Generates SQLite schema, TypeScript types, and services from Nix schema.
 *
 * Usage: nix eval --json -f schema/default.nix | bun schema/codegen.ts
 */

import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

// ============================================================================
// Types
// ============================================================================

export interface Column {
  type: string;
  pk: boolean;
  auto: boolean;
  required: boolean;
  unique: boolean;
  default: string | null;
  references: string | null;
}

export type Tables = Record<string, Record<string, Column>>;

export interface Expr {
  _t: "field" | "rel" | "lit" | "bin" | "un" | "agg";
  [key: string]: unknown;
}

export interface Cascade {
  entity: string;
  via: string | null;
  set: Record<string, string>;
}

export interface Effect {
  emit: string | null;
  notify: { channel: string; template: string; to: string } | null;
  call: { service: string; action: string } | null;
}

export interface Operation {
  guard: Expr | null;
  set: Record<string, string>;
  cascade: Cascade[];
  effects: Effect[];
}

export type Operations = Record<string, Record<string, Operation>>;

export interface Schema {
  tables: Tables;
  operations: Operations;
}

// ============================================================================
// SQL Generation
// ============================================================================

const TS_TYPE_MAP: Record<string, string> = {
  integer: "number",
  text: "string",
  real: "number",
  blob: "Uint8Array",
};

export function pascalCase(s: string): string {
  return s.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
}

export function camelCase(s: string): string {
  return s.replace(/_(\w)/g, (_, c) => c.toUpperCase());
}

function quoteReserved(name: string): string {
  // SQLite reserved words that need quoting
  const reserved = ["transaction", "order", "group", "index"];
  return reserved.includes(name.toLowerCase()) ? `[${name}]` : name;
}

export function sqlType(col: Column): string {
  const parts = [col.type.toUpperCase()];
  if (col.pk) parts.push("PRIMARY KEY");
  if (col.auto) parts.push("AUTOINCREMENT");
  if (col.required && !col.pk) parts.push("NOT NULL");
  if (col.unique) parts.push("UNIQUE");
  if (col.default !== null) parts.push(`DEFAULT ${col.default}`);
  if (col.references !== null) {
    // Quote table name in references if reserved
    const ref = col.references.replace(/^(\w+)/, (_, table) => quoteReserved(table));
    parts.push(`REFERENCES ${ref}`);
  }
  return parts.join(" ");
}

export function genSQL(tables: Tables): string {
  const stmts: string[] = [];
  for (const [table, cols] of Object.entries(tables)) {
    const defs: string[] = [];
    for (const [col, c] of Object.entries(cols)) {
      defs.push(`    ${col} ${sqlType(c)}`);
    }
    const tableName = quoteReserved(table);
    stmts.push(`CREATE TABLE IF NOT EXISTS ${tableName} (\n${defs.join(",\n")}\n);`);
  }
  return stmts.join("\n\n") + "\n";
}

// ============================================================================
// Types Generation
// ============================================================================

export function tsType(sqliteType: string): string {
  return TS_TYPE_MAP[sqliteType] ?? "unknown";
}

export function genRowInterface(table: string, cols: Record<string, Column>): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    const ts = tsType(c.type);
    const nullable = !c.pk && !c.required ? " | null" : "";
    fields.push(`  ${col}: ${ts}${nullable};`);
  }
  return `export interface ${name} {\n${fields.join("\n")}\n}`;
}

export function genInputInterface(table: string, cols: Record<string, Column>): string {
  const name = pascalCase(table);
  const fields: string[] = [];
  for (const [col, c] of Object.entries(cols)) {
    if (c.pk && c.auto) continue;
    const ts = tsType(c.type);
    const opt = c.required ? "" : "?";
    fields.push(`  ${col}${opt}: ${ts};`);
  }
  return `export interface ${name}Input {\n${fields.join("\n")}\n}`;
}

export function genTypes(tables: Tables): string {
  const chunks: string[] = ["// Generated by schema/codegen.ts — do not edit\n"];
  for (const [table, cols] of Object.entries(tables)) {
    chunks.push(genRowInterface(table, cols));
    chunks.push(genInputInterface(table, cols));
  }
  return chunks.join("\n\n") + "\n";
}

// ============================================================================
// Expression Compilation
// ============================================================================

export function compileExpr(expr: Expr, ctx: string): string {
  switch (expr._t) {
    case "field":
      return `${ctx}.${expr.name}`;

    case "rel":
      // Related entity field - generates variable reference
      // The service will need to load this relation
      return `_rel_${expr.entity}.${expr.field}`;

    case "lit":
      const val = expr.value;
      if (typeof val === "string") return JSON.stringify(val);
      if (typeof val === "boolean") return val ? "true" : "false";
      return String(val);

    case "bin":
      const left = compileExpr(expr.left as Expr, ctx);
      const right = compileExpr(expr.right as Expr, ctx);
      const op = expr.op === "==" ? "===" : expr.op === "!=" ? "!==" : expr.op;
      return `(${left} ${op} ${right})`;

    case "un":
      const arg = compileExpr(expr.arg as Expr, ctx);
      if (expr.op === "isNull") return `(${arg} === null)`;
      if (expr.op === "notNull") return `(${arg} !== null)`;
      return `${expr.op}(${arg})`;

    case "agg":
      // Aggregations need special handling
      return `/* AGG: ${expr.op} on ${(expr.rel as Expr).entity} */`;

    default:
      return "/* unknown expr */";
  }
}

// Extract relations used in an expression
export function extractRelations(expr: Expr | null): string[] {
  if (!expr) return [];
  const rels: string[] = [];

  function walk(e: Expr) {
    if (e._t === "rel") {
      rels.push(e.entity as string);
    } else if (e._t === "bin") {
      walk(e.left as Expr);
      walk(e.right as Expr);
    } else if (e._t === "un") {
      walk(e.arg as Expr);
    }
  }

  walk(expr);
  return [...new Set(rels)];
}

// ============================================================================
// Service Generation
// ============================================================================

function genServiceImports(): string {
  return `import { Database } from "bun:sqlite";
import type * as T from "./types";

export type Result<D> =
  | { ok: true; data: D }
  | { ok: false; error: string; code: "not_found" | "invalid" | "bad_state" };

export interface Effect {
  type: "emit" | "notify" | "call";
  payload: unknown;
}

export interface OpResult<D> extends Result<D> {
  effects?: Effect[];
}
`;
}

function genCrudService(entity: string, cols: Record<string, Column>): string {
  const Entity = pascalCase(entity);
  const tableName = entity === "transaction" ? "[transaction]" : entity;

  const colNames = Object.keys(cols);
  const inputCols = colNames.filter(c => !(cols[c].pk && cols[c].auto));
  const requiredCols = inputCols.filter(c => cols[c].required);

  return `
// ============================================================================
// ${Entity} CRUD
// ============================================================================

export function find${Entity}ById(db: Database, id: number): T.${Entity} | null {
  return db.query("SELECT * FROM ${tableName} WHERE id = ?").get(id) as T.${Entity} | null;
}

export function findAll${Entity}s(db: Database): T.${Entity}[] {
  return db.query("SELECT * FROM ${tableName} ORDER BY id").all() as T.${Entity}[];
}

export function create${Entity}(db: Database, input: T.${Entity}Input): Result<{ id: number }> {
  ${requiredCols.length > 0 ? `// Validate required fields
  ${requiredCols.map(c => `if (input.${c} === undefined) return { ok: false, error: "${c} is required", code: "invalid" };`).join("\n  ")}` : ""}

  // Build dynamic insert - only include provided fields, let DB handle defaults
  const cols: string[] = [];
  const vals: unknown[] = [];
  ${inputCols.map(c => `if (input.${c} !== undefined) { cols.push("${c}"); vals.push(input.${c}); }`).join("\n  ")}

  const result = db.query(\`
    INSERT INTO ${tableName} (\${cols.join(", ")})
    VALUES (\${cols.map(() => "?").join(", ")})
    RETURNING id
  \`).get(...vals) as { id: number };

  return { ok: true, data: { id: result.id } };
}

export function update${Entity}(db: Database, id: number, input: Partial<T.${Entity}Input>): Result<{ id: number }> {
  const existing = find${Entity}ById(db, id);
  if (!existing) return { ok: false, error: "not found", code: "not_found" };

  const sets: string[] = [];
  const vals: unknown[] = [];
  ${inputCols.map(c => `if (input.${c} !== undefined) { sets.push("${c} = ?"); vals.push(input.${c}); }`).join("\n  ")}

  if (sets.length > 0) {
    vals.push(id);
    db.query(\`UPDATE ${tableName} SET \${sets.join(", ")} WHERE id = ?\`).run(...vals);
  }

  return { ok: true, data: { id } };
}

export function delete${Entity}(db: Database, id: number): Result<{ deleted: true }> {
  const existing = find${Entity}ById(db, id);
  if (!existing) return { ok: false, error: "not found", code: "not_found" };

  db.query("DELETE FROM ${tableName} WHERE id = ?").run(id);
  return { ok: true, data: { deleted: true } };
}
`;
}

function genOperationService(entity: string, opName: string, op: Operation, tables: Tables): string {
  const Entity = pascalCase(entity);
  const OpName = camelCase(opName);
  const tableName = entity === "transaction" ? "[transaction]" : entity;

  const relations = extractRelations(op.guard);
  const guardCode = op.guard ? compileExpr(op.guard, entity) : "true";

  // Generate relation loading
  const relLoads = relations.map(rel => {
    // Find FK column
    const fkCol = `${rel}_id`;
    return `  const _rel_${rel} = db.query("SELECT * FROM ${rel} WHERE id = ?").get(${entity}.${fkCol}) as T.${pascalCase(rel)} | null;
  if (!_rel_${rel}) return { ok: false, error: "${rel} not found", code: "invalid" };`;
  }).join("\n");

  // Generate set clause
  const setEntries = Object.entries(op.set);
  const setCode = setEntries.length > 0
    ? `db.query("UPDATE ${tableName} SET ${setEntries.map(([k]) => `${k} = ?`).join(", ")} WHERE id = ?").run(${setEntries.map(([_, v]) => JSON.stringify(v)).join(", ")}, id);`
    : "// No fields to set";

  // Generate cascade updates
  const cascadeCode = op.cascade.map(c => {
    // Use single quotes for SQL string literals
    const setClause = Object.entries(c.set).map(([k, v]) => `${k} = '${v}'`).join(", ");
    if (c.via) {
      // Check if via is a junction table (contains underscore and exists as table)
      // or a direct FK column name
      if (c.via.includes("_") && c.via !== `${entity}_id`) {
        // Junction table: via = "transaction_ticket"
        return `  db.query(\`UPDATE ${c.entity} SET ${setClause} WHERE id IN (SELECT ${c.entity}_id FROM ${c.via} WHERE ${entity}_id = ?)\`).run(id);`;
      } else {
        // Direct FK column: via = "performance_id"
        return `  db.query("UPDATE ${c.entity} SET ${setClause} WHERE ${c.via} = ?").run(id);`;
      }
    } else {
      // Default: FK on target entity named {entity}_id
      return `  db.query("UPDATE ${c.entity} SET ${setClause} WHERE ${entity}_id = ?").run(id);`;
    }
  }).join("\n");

  // Generate effects
  const effectsCode = op.effects.map(e => {
    if (e.emit) return `    { type: "emit", payload: { event: ${JSON.stringify(e.emit)}, ${entity} } }`;
    if (e.notify) return `    { type: "notify", payload: ${JSON.stringify(e.notify)} }`;
    if (e.call) return `    { type: "call", payload: ${JSON.stringify(e.call)} }`;
    return "";
  }).filter(Boolean).join(",\n");

  return `
export function ${OpName}${Entity}(db: Database, id: number): OpResult<{ id: number; status: string }> {
  const ${entity} = find${Entity}ById(db, id);
  if (!${entity}) return { ok: false, error: "not found", code: "not_found" };

${relLoads}

  // Guard: ${op.guard ? "check preconditions" : "none"}
  if (!(${guardCode})) {
    return { ok: false, error: "precondition failed for ${opName}", code: "bad_state" };
  }

  // Execute in transaction
  const run = db.transaction(() => {
    ${setCode}
${cascadeCode}
  });
  run();

  return {
    ok: true,
    data: { id, status: ${setEntries.find(([k]) => k === "status") ? JSON.stringify(setEntries.find(([k]) => k === "status")![1]) : '"updated"'} },
    effects: [
${effectsCode}
    ],
  };
}
`;
}

export function genServices(schema: Schema): string {
  const chunks: string[] = [
    "// Generated by schema/codegen.ts — do not edit\n",
    genServiceImports(),
  ];

  // Generate CRUD for each entity
  for (const [entity, cols] of Object.entries(schema.tables)) {
    chunks.push(genCrudService(entity, cols));
  }

  // Generate operations
  for (const [entity, ops] of Object.entries(schema.operations)) {
    for (const [opName, op] of Object.entries(ops)) {
      chunks.push(genOperationService(entity, opName, op, schema.tables));
    }
  }

  return chunks.join("\n");
}

// ============================================================================
// Effects Interface
// ============================================================================

function genEffectsInterface(schema: Schema): string {
  const events = new Set<string>();
  const notifyTemplates = new Set<string>();
  const calls = new Set<string>();

  for (const ops of Object.values(schema.operations)) {
    for (const op of Object.values(ops)) {
      for (const e of op.effects) {
        if (e.emit) events.add(e.emit);
        if (e.notify) notifyTemplates.add(e.notify.template);
        if (e.call) calls.add(`${e.call.service}.${e.call.action}`);
      }
    }
  }

  return `// Generated by schema/codegen.ts — do not edit

// Events emitted by operations
export type Event =
${[...events].map(e => `  | "${e}"`).join("\n") || "  | never"};

// Notification templates
export type NotifyTemplate =
${[...notifyTemplates].map(t => `  | "${t}"`).join("\n") || "  | never"};

// External service calls
export type ServiceCall =
${[...calls].map(c => `  | "${c}"`).join("\n") || "  | never"};

// Effect handlers interface
export interface EffectHandlers {
  emit(event: Event, data: unknown): Promise<void>;
  notify(channel: string, template: NotifyTemplate, to: string, data: unknown): Promise<void>;
  call(service: string, action: string, data: unknown): Promise<unknown>;
}
`;
}

// ============================================================================
// Main
// ============================================================================

if (import.meta.main) {
  const input = await Bun.stdin.text();
  const schema: Schema = JSON.parse(input);

  const outDir = join(import.meta.dir, "..", "src", "generated");
  mkdirSync(outDir, { recursive: true });

  writeFileSync(join(outDir, "schema.sql"), genSQL(schema.tables));
  writeFileSync(join(outDir, "types.ts"), genTypes(schema.tables));
  writeFileSync(join(outDir, "services.ts"), genServices(schema));
  writeFileSync(join(outDir, "effects.ts"), genEffectsInterface(schema));

  console.log("wrote src/generated/schema.sql");
  console.log("wrote src/generated/types.ts");
  console.log("wrote src/generated/services.ts");
  console.log("wrote src/generated/effects.ts");
}
